export const SELECT_REMINDER = 'SELECT_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const SAVE_REMINDER = 'SAVE_REMINDER';
export const INCREASE_CURRENT_MONTH = 'INCREASE_CURRENT_MONTH';
export const DECREASE_CURRENT_MONTH = 'DECREASE_CURRENT_MONTH';